In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import *

In [2]:
df = pd.read_csv('heart.csv')
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [3]:
df.sample(10)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
996,56,0,0,134,409,0,0,150,1,1.9,1,2,3,0
688,56,0,0,200,288,1,0,133,1,4.0,0,2,3,0
564,56,1,0,132,184,0,0,105,1,2.1,1,1,1,0
1015,58,1,0,128,216,0,0,131,1,2.2,1,3,3,0
578,62,0,0,140,394,0,0,157,0,1.2,1,0,2,1
171,56,1,0,130,283,1,0,103,1,1.6,0,0,3,0
919,38,1,3,120,231,0,1,182,1,3.8,1,0,3,0
264,58,0,0,170,225,1,0,146,1,2.8,1,2,1,0
855,46,1,1,101,197,1,1,156,0,0.0,2,0,3,1
803,52,1,0,112,230,0,1,160,0,0.0,2,1,2,0

In [4]:
df.shape

(1025, 14)

In [5]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [6]:
X

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3

In [7]:
y

0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 1025, dtype: int64

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

log = LogisticRegression()
dt = DecisionTreeClassifier()

log.fit(X_train,y_train)
dt.fit(X_train,y_train)

y_pred = log.predict(X_test)
y_pred1 = dt.predict(X_test)


print(f'Accuracy of LogisticRegression : {accuracy_score(y_test,y_pred)}')
print(f'Accuracy of DecisionTree : {accuracy_score(y_test,y_pred1)}')

Accuracy of LogisticRegression : 0.8536585365853658
Accuracy of DecisionTree : 0.9804878048780488

C:\Users\Nihar\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [9]:
print(f'confusion_matrix of LogisticRegression : \n {confusion_matrix(y_test,y_pred)}')
print('\n')
print(f'confusion_matrix of DecisionTree : \n {confusion_matrix(y_test,y_pred1)}')

confusion_matrix of LogisticRegression :
 [[82 23]
 [ 7 93]]


confusion_matrix of DecisionTree :
 [[101   4]
 [  0 100]]

In [10]:
lr_cof = pd.DataFrame(confusion_matrix(y_test,y_pred),columns=[1,0])
lr_cof[' '] = [1, 0]
lr_cof.set_index(' ',inplace=True)
lr_cof

    1   0

1  82  23
0   7  93

In [11]:
df = pd.DataFrame(confusion_matrix(y_test,y_pred),columns=[1,0])
df[' '] = [1, 0]
table1 = pd.pivot_table(data=df,index=[' '])
table1

    0   1

0  93   7
1  23  82

In [12]:
print('Logistic Regression'.center(50))
print('__'*25)
print(f'Confusion Matrix : \n {pd.DataFrame(confusion_matrix(y_test,y_pred))}')
print('_ '*25)
print('Accuracy : ',accuracy_score(y_test,y_pred))
print('Precision : ',precision_score(y_test,y_pred))
print('Recall : ',recall_score(y_test,y_pred))
print('F1 score : ',f1_score(y_test,y_pred))

               Logistic Regression
__________________________________________________
Confusion Matrix :
     0   1
0  82  23
1   7  93
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Accuracy :  0.8536585365853658
Precision :  0.8017241379310345
Recall :  0.93
F1 score :  0.8611111111111112

In [13]:
print('Decision Tree'.center(50))
print('__'*25)
print(f'Confusion Matrix : \n {pd.DataFrame(confusion_matrix(y_test,y_pred1))}')
print('_ '*25)
print('Accuracy : ',accuracy_score(y_test,y_pred1))
print('Precision : ',precision_score(y_test,y_pred1))
print('Recall : ',recall_score(y_test,y_pred1))
print('F1 score : ',f1_score(y_test,y_pred1))

                  Decision Tree
__________________________________________________
Confusion Matrix :
      0    1
0  101    4
1    0  100
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Accuracy :  0.9804878048780488
Precision :  0.9615384615384616
Recall :  1.0
F1 score :  0.9803921568627451

In [14]:
precision_score(y_test,y_pred, average=None)
# By deafault precsion value is for positive(1) which is present in index[1] rather than zero class

array([0.92134831, 0.80172414])

In [15]:
recall_score(y_test,y_pred, average=None)
# By deafault recall value is for positive(1) which is present in index[1] rather than zero class

array([0.78095238, 0.93      ])

In [16]:
f1_score(y_test,y_pred,average=None)

array([0.84536082, 0.86111111])

In [17]:
print('Logistic Regression'.center(50))
print('__'*25)
print(f'Confusion Matrix : \n {pd.DataFrame(confusion_matrix(y_test,y_pred))}')
print('_ '*25)
print('Accuracy : ',accuracy_score(y_test,y_pred))
print('_ '*25)
print('Precision : ',precision_score(y_test,y_pred,average=None))
print('_ '*25)
print('Recall : ',recall_score(y_test,y_pred,average=None))
print('_ '*25)
print('F1 score : ',f1_score(y_test,y_pred,average=None))

               Logistic Regression
__________________________________________________
Confusion Matrix :
     0   1
0  82  23
1   7  93
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Accuracy :  0.8536585365853658
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Precision :  [0.92134831 0.80172414]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Recall :  [0.78095238 0.93      ]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
F1 score :  [0.84536082 0.86111111]

In [18]:
print('Logistic Regression'.center(50))
print('__'*25)
print(f'Confusion Matrix : \n {pd.DataFrame(confusion_matrix(y_test,y_pred))}')
print('_ '*25)
print('Accuracy : ',accuracy_score(y_test,y_pred))
print('_ '*25)
print('Precision : ',precision_score(y_test,y_pred,average='macro'))
print('_ '*25)
print('Recall : ',recall_score(y_test,y_pred,average='macro'))
print('_ '*25)
print('F1 score : ',f1_score(y_test,y_pred,average='macro'))

               Logistic Regression
__________________________________________________
Confusion Matrix :
     0   1
0  82  23
1   7  93
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Accuracy :  0.8536585365853658
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Precision :  0.861536226268888
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Recall :  0.8554761904761905
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
F1 score :  0.8532359679266897

In [19]:
print('Logistic Regression'.center(50))
print('__'*25)
print(f'Confusion Matrix : \n {pd.DataFrame(confusion_matrix(y_test,y_pred))}')
print('_ '*25)
print('Accuracy : ',accuracy_score(y_test,y_pred))
print('_ '*25)
print('Precision : ',precision_score(y_test,y_pred,average='weighted'))
print('_ '*25)
print('Recall : ',recall_score(y_test,y_pred,average='weighted'))
print('_ '*25)
print('F1 score : ',f1_score(y_test,y_pred,average='weighted'))

               Logistic Regression
__________________________________________________
Confusion Matrix :
     0   1
0  82  23
1   7  93
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Accuracy :  0.8536585365853658
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Precision :  0.8629950576917624
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Recall :  0.8536585365853658
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
F1 score :  0.853043891263655

In [20]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      0.78      0.85       105
           1       0.80      0.93      0.86       100

    accuracy                           0.85       205
   macro avg       0.86      0.86      0.85       205
weighted avg       0.86      0.85      0.85       205

# Decision tree

In [21]:
print('Decision tree'.center(50))
print('__'*25)
print(f'Confusion Matrix : \n {pd.DataFrame(confusion_matrix(y_test,y_pred1))}')
print('_ '*25)
print('Accuracy : ',accuracy_score(y_test,y_pred1))
print('_ '*25)
print('Precision : ',precision_score(y_test,y_pred1,average=None))
print('_ '*25)
print('Recall : ',recall_score(y_test,y_pred1,average=None))
print('_ '*25)
print('F1 score : ',f1_score(y_test,y_pred1,average=None))

                  Decision tree
__________________________________________________
Confusion Matrix :
      0    1
0  101    4
1    0  100
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Accuracy :  0.9804878048780488
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Precision :  [1.         0.96153846]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Recall :  [0.96190476 1.        ]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
F1 score :  [0.98058252 0.98039216]

In [22]:
print('Decision tree'.center(50))
print('__'*25)
print(f'Confusion Matrix : \n {pd.DataFrame(confusion_matrix(y_test,y_pred1))}')
print('_ '*25)
print('Accuracy : ',accuracy_score(y_test,y_pred1))
print('_ '*25)
print('Precision : ',precision_score(y_test,y_pred1,average='macro'))
print('_ '*25)
print('Recall : ',recall_score(y_test,y_pred1,average='macro'))
print('_ '*25)
print('F1 score : ',f1_score(y_test,y_pred1,average='macro'))

                  Decision tree
__________________________________________________
Confusion Matrix :
      0    1
0  101    4
1    0  100
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Accuracy :  0.9804878048780488
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Precision :  0.9807692307692308
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Recall :  0.980952380952381
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
F1 score :  0.9804873405672949

In [23]:
print('Decision tree'.center(50))
print('__'*25)
print(f'Confusion Matrix : \n {pd.DataFrame(confusion_matrix(y_test,y_pred1))}')
print('_ '*25)
print('Accuracy : ',accuracy_score(y_test,y_pred1))
print('_ '*25)
print('Precision : ',precision_score(y_test,y_pred1,average='weighted'))
print('_ '*25)
print('Recall : ',recall_score(y_test,y_pred1,average='weighted'))
print('_ '*25)
print('F1 score : ',f1_score(y_test,y_pred1,average='weighted'))

                  Decision tree
__________________________________________________
Confusion Matrix :
      0    1
0  101    4
1    0  100
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Accuracy :  0.9804878048780488
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Precision :  0.9812382739212008
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Recall :  0.9804878048780488
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
F1 score :  0.9804896621210643

In [24]:
print(classification_report(y_test, y_pred1))

              precision    recall  f1-score   support

           0       1.00      0.96      0.98       105
           1       0.96      1.00      0.98       100

    accuracy                           0.98       205
   macro avg       0.98      0.98      0.98       205
weighted avg       0.98      0.98      0.98       205